### PR TITLE
Formatted README.md 

### LINKED ISSUE #18: Format the already present quotes
Some of the contributors have added their quotes. But it is not in proper format as specified in [CONTRIBUTING.md](https://github.com/ab-anand/fav-quote/blob/master/CONTRIBUTING.md)

You can check out the Contributing Guidelines and format them properly.

### PR DESCRIPTION
**Pull request by mohitrakhade20**
Formatted all the quotes 📝 and added some good emojis 🥇  [ resolved #18 ]

### CODE REVIEW

**Comment by ab-anand** [comment]
Hey @mohitrakhade20 ,
The work looks good. Except for the formatting of the Quotes. I think you missed to check the Contributing Guidelines.
Please modify your PR accordingly.

Thanks

**Comment by mohitrakhade20** [comment]
I will back the improved version, Thanks

**Comment by mohitrakhade20** [comment]
Have a look @ab-anand

**Comment by ab-anand** [comment]
This looks awesome,
Great work @mohitrakhade20 👍

**Comment by saideepesh000** [comment]
@ab-anand, I thought it was a first-come-first-serve issue, I was already working on it. Thanks for neglecting me.

**Pull request merged**
