### PR TITLE
added  qoute [ #1 resolve ]

### PR DESCRIPTION
**Pull request by mohitrakhade20**

### CODE REVIEW

**Review by ab-anand — COMMENTED** [review]
Hey @mohitrakhade20 ,
I've done some changes in master. You might wanna update your cloned version first then do raise this PR

**Review by ab-anand — CHANGES_REQUESTED** [review]
Hey @mohitrakhade20 .
I've done some changes in the repo. Please consider working on the updated repo and raise a PR again.
Thanks

**Comment by mohitrakhade20** [comment]
now you can merge this PR

**Review by ab-anand — APPROVED** [review]
I've done the changes

**Pull request merged**
